macro(assign_source_group SOURCES)
    foreach(FILE IN LISTS ${SOURCES})
        get_filename_component(PARENT_DIR "${FILE}" DIRECTORY)
        file(RELATIVE_PATH REL_DIR "${CMAKE_CURRENT_SOURCE_DIR}" "${PARENT_DIR}")
        string(REPLACE "/" "\\" GROUP_NAME "${REL_DIR}")
        source_group("${GROUP_NAME}" FILES "${FILE}")
    endforeach()
endmacro()